monacodelisa/Angular-Headless-Hashnode

angular-v16/src/app/app.module.ts, angular-v16/src/app/components/header/header.component.html, angular-v16/src/app/components/header/header.component.spec.ts, angular-v16/src/app/components/header/header.component.ts
=> Header Component 

CONTRIBUTING.md, README.md, angular-v16/src/app/components/footer/footer.component.scss, angular-v16/src/app/components/header/header.component.html, angular-v16/src/app/components/header/header.component.scss, angular-v16/src/app/components/header/header.component.ts, angular-v16/src/index.html, angular-v16/src/styles.scss
- [x ] The commit message follows the guidelines
=> Header layout

README.md
=> found Apollo readme update

angular-v16/src/app/components/footer/footer.component.html, angular-v16/src/app/components/footer/footer.component.scss, angular-v16/src/app/components/footer/footer.component.ts, angular-v16/src/app/components/header/header.component.html, angular-v16/src/app/components/header/header.component.scss
=> header & footer layout

README.md
=> discord link in readme

.github/PULL_REQUEST_TEMPLATE.md, angular-v16/src/app/app.component.html, angular-v16/src/app/app.component.scss, angular-v16/src/app/app.component.ts, angular-v16/src/app/components/header/header.component.html, angular-v16/src/app/components/header/header.component.ts, angular-v16/src/app/services/theme.service.spec.ts, angular-v16/src/app/services/theme.service.ts
=> feat(sitewide):dynamic theme switching using signals

.github/PULL_REQUEST_TEMPLATE.md
=> docs(pr tepmlate)

README.md
=> docs(readme): links to live version added

README.md
=> docs(readme):most issues include a video

angular-v16/package-lock.json, angular-v16/package.json, angular-v16/src/app/app.component.html, angular-v16/src/app/app.module.ts, angular-v16/src/app/components/posts/posts.component.html, angular-v16/src/app/components/posts/posts.component.scss, angular-v16/src/app/components/posts/posts.component.spec.ts, angular-v16/src/app/components/posts/posts.component.ts, angular-v16/src/app/graphql.module.ts, angular-v16/src/app/graphql.operations.ts, angular-v16/src/styles.scss, angular-v16/tsconfig.json
=> feat(apollo): integrated Apollo Angular for GraphQL queries

README.md
=> docs(readme):update

CONTRIBUTING.md, angular-v16/src/app/graphql.operations.ts
=> feat(graphql): query blog url set to angular-headless.hashnode.dev

angular-v16/src/app/components/posts/posts.component.ts, angular-v16/src/app/services/blog.service.spec.ts, angular-v16/src/app/services/blog.service.ts
=> feat(service): blog service created and injected

angular-v16/src/app/components/header/header.component.html, angular-v16/src/app/components/header/header.component.ts, angular-v16/src/app/components/posts/posts.component.ts, angular-v16/src/app/graphql.operations.ts, angular-v16/src/app/services/blog.service.ts
=> feat(header): blog title and social links

angular-v16/src/app/app.component.scss, angular-v16/src/app/components/posts/posts.component.html, angular-v16/src/app/components/posts/posts.component.scss, angular-v16/src/app/components/posts/posts.component.ts, angular-v16/src/styles.scss
=> feat(posts): grid to list view toggle

angular-v16/src/app/components/posts/posts.component.html, angular-v16/src/app/graphql.operations.ts
=> feat(posts): post cover image

angular-v16/src/app/graphql.operations.ts
=> feat(posts): publication id

angular-v16/src/app/graphql.operations.ts
=> feat(): post content html

angular-v17/src/app/app.component.html, angular-v17/src/app/app.component.scss, angular-v17/src/app/app.component.ts, angular-v17/src/app/components/footer/footer.component.html, angular-v17/src/app/components/footer/footer.component.scss, angular-v17/src/app/components/footer/footer.component.spec.ts, angular-v17/src/app/components/footer/footer.component.ts
=> feat(footer):component created with required elements v17

angular-v16/src/app/components/header/header.component.ts, angular-v17/src/app/app.component.html, angular-v17/src/app/app.component.ts, angular-v17/src/app/components/header/header.component.html, angular-v17/src/app/components/header/header.component.ts, angular-v17/src/app/services/theme.service.spec.ts, angular-v17/src/app/services/theme.service.ts
=> feat(header): theming for v17 with signals

.github/PULL_REQUEST_TEMPLATE.md, angular-v17/src/app/app.component.html, angular-v17/src/app/app.component.ts, angular-v17/src/app/components/posts/posts.component.html, angular-v17/src/app/components/posts/posts.component.scss, angular-v17/src/app/components/posts/posts.component.spec.ts, angular-v17/src/app/components/posts/posts.component.ts
=> feat(posts): displaying dummy posts

angular-v17/package-lock.json, angular-v17/package.json, angular-v17/src/app/app.config.ts, angular-v17/src/app/components/posts/posts.component.html, angular-v17/src/app/components/posts/posts.component.ts, angular-v17/src/app/graphql.operations.ts
=> feat(posts): apollo angular v17 graphql blog posts

angular-v17/src/app/components/posts/posts.component.ts, angular-v17/src/app/services/blog.service.spec.ts, angular-v17/src/app/services/blog.service.ts
=> feat(service): blog serice apollo angular graphql

angular-v16/src/app/components/posts/posts.component.html, angular-v16/src/app/graphql.operations.ts, angular-v17/src/app/components/footer/footer.component.ts, angular-v17/src/app/components/header/header.component.html, angular-v17/src/app/components/header/header.component.ts, angular-v17/src/app/components/posts/posts.component.html, angular-v17/src/app/components/posts/posts.component.ts, angular-v17/src/app/graphql.operations.ts
=> feat(header, posts, footer): blog title post cover image

angular-v16/netlify.toml
=> netlify adjusting-1

README.md
=> feat(deployment): monorepo angular v17 deployed to netlify

angular-v17/src/app/components/header/header.component.html
=> feat(header): minor adjustment

angular-v16/src/app/app-routing.module.ts, angular-v16/src/app/app.component.html, angular-v16/src/app/app.module.ts
=> feat(routing): angular v16 native

angular-v16/src/app/components/post/post.component.html, angular-v16/src/app/components/post/post.component.scss, angular-v16/src/app/components/post/post.component.ts
=> feat(post): basic styling and layout of single post

angular-hashnode/src/app/app.component.scss
=> fix(toolbar height): presentation site

angular-hashnode/src/index.html
=> feat(presentation site): og image for social share

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, README.md
=> docs(redme): templates and more

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> docs(issues): templates

angular-v17-AnguMAT/angular.json, angular-v17-AnguMAT/src/app/app.component.html, angular-v17-AnguMAT/src/app/app.component.scss, angular-v17-AnguMAT/src/app/app.component.ts, angular-v17-AnguMAT/src/app/app.config.ts, angular-v17-AnguMAT/src/app/components/header/header.component.html, angular-v17-AnguMAT/src/app/components/header/header.component.scss, angular-v17-AnguMAT/src/app/components/header/header.component.ts, angular-v17-AnguMAT/src/app/services/theme.service.spec.ts, angular-v17-AnguMAT/src/app/services/theme.service.ts, angular-v17-AnguMAT/src/styles.scss, angular-v17-AnguMAT/src/theme.scss
=> added themeToggle functionality.

angular-v16/netlify.toml
=> feat(angular-v16): ignore other builds

angular-hashnode/src/assets/JSON/live-sites-17.json, angular-v16/netlify.toml
=> feat(presentation site): links to v17 sites

angular-v17/src/app/components/header/header.component.html, angular-v17/src/app/components/header/header.component.ts, angular-v17/src/app/models/social-links.ts
#95 
PR includes the following changes:
- Added the Pipe import
- destructed the links to remove __typename 
- fixed the layout to remove unnecessary div renders
=> fix: display of icons on header dynamically

angular-v17/src/app/components/header/header.component.html
=> fix(header): angular v17 remove static social links

angular-v17-AnguMAT/src/app/components/header/header.component.html
=> fix(header): angular-v17-angumat no need of button around mat-icons

angular-v17-PrimeNG/package-lock.json, angular-v17-PrimeNG/package.json, angular-v17-PrimeNG/src/app/app.config.ts, angular-v17-PrimeNG/src/app/components/footer/footer.component.html, angular-v17-PrimeNG/src/app/components/footer/footer.component.scss, angular-v17-PrimeNG/src/app/components/footer/footer.component.ts, angular-v17-PrimeNG/src/app/graphql.operations.ts, angular-v17-PrimeNG/src/app/services/blog.service.spec.ts, angular-v17-PrimeNG/src/app/services/blog.service.ts
=> feat(angular-v17-primeng): added elements and styled footer component

.github/PULL_REQUEST_TEMPLATE.md, angular-v17-PrimeNG/src/app/app.component.html, angular-v17-PrimeNG/src/app/app.component.scss, angular-v17-PrimeNG/src/app/components/footer/footer.component.html, angular-v17-PrimeNG/src/app/components/footer/footer.component.scss, angular-v17-PrimeNG/src/app/components/footer/footer.component.ts, angular-v17-PrimeNG/src/app/components/header/header.component.html, angular-v17-PrimeNG/src/app/components/header/header.component.ts, angular-v17-PrimeNG/src/app/models/social-links.ts, angular-v17-PrimeNG/src/styles.scss
=> feat(header): social links blog title v17-primeNG

.github/PULL_REQUEST_TEMPLATE.md
=> docs(update): pr template

angular-v17-AnguMAT/src/app/components/footer/footer.component.html, angular-v17-AnguMAT/src/app/components/footer/footer.component.scss, angular-v17-AnguMAT/src/app/components/footer/footer.component.ts
=> add footer component.

angular-v17-AnguMAT/angular.json, angular-v17-AnguMAT/package-lock.json, angular-v17-AnguMAT/package.json
=> social links and icons

angular-v17-AnguMAT/package-lock.json, angular-v17-AnguMAT/package.json, angular-v17-AnguMAT/src/app/app.component.html, angular-v17-AnguMAT/src/app/app.config.ts, angular-v17-AnguMAT/src/app/app.routes.ts, angular-v17-AnguMAT/src/app/components/header/header.component.scss, angular-v17-AnguMAT/src/app/components/header/header.component.ts, angular-v17-AnguMAT/src/app/graphql.operations.ts, angular-v17-AnguMAT/src/app/models/post.ts, angular-v17-AnguMAT/src/app/models/social-links.ts, angular-v17-AnguMAT/src/app/pages/post-detail/post-detail.component.html, angular-v17-AnguMAT/src/app/pages/post-detail/post-detail.component.scss, angular-v17-AnguMAT/src/app/pages/post-detail/post-detail.component.spec.ts, angular-v17-AnguMAT/src/app/pages/post-detail/post-detail.component.ts, angular-v17-AnguMAT/src/app/pages/posts/posts.component.html, angular-v17-AnguMAT/src/app/pages/posts/posts.component.scss, angular-v17-AnguMAT/src/app/pages/posts/posts.component.spec.ts, angular-v17-AnguMAT/src/app/pages/posts/posts.component.ts, angular-v17-AnguMAT/src/app/services/blog.service.spec.ts, angular-v17-AnguMAT/src/app/services/blog.service.ts
closes #178 
PR includes the following changes
- configured routing and angular config
- added Apollo angular package
- created blog service to fetch post and post details
- API integration for the posts and post detail
- used mat-grid-list for posts rendering
- used existing layout from v17 native project for post detail page
=> feat: Retrieve, style and display blog posts v17 Angular Material

angular-v17-modMAT/netlify.toml
=> feat(angular-v17-modMAT): netlify.tom publish path

angular-v17-AnguMAT/src/app/components/header/header.component.scss
=> fix(angular-v17-AnguMAT): font awesome styling svg

README.md
=> doscs(readme): updated live sites info

angular-v17-PrimeNG/src/app/app.component.html, angular-v17-PrimeNG/src/app/app.config.ts, angular-v17-PrimeNG/src/app/app.routes.ts, angular-v17-PrimeNG/src/app/models/post.ts, angular-v17-PrimeNG/src/app/pages/post-detail/post-detail.component.html, angular-v17-PrimeNG/src/app/pages/post-detail/post-detail.component.scss, angular-v17-PrimeNG/src/app/pages/post-detail/post-detail.component.spec.ts, angular-v17-PrimeNG/src/app/pages/post-detail/post-detail.component.ts, angular-v17-PrimeNG/src/app/pages/posts/posts.component.html, angular-v17-PrimeNG/src/app/pages/posts/posts.component.scss, angular-v17-PrimeNG/src/app/pages/posts/posts.component.spec.ts, angular-v17-PrimeNG/src/app/pages/posts/posts.component.ts, angular-v17-PrimeNG/src/styles.scss
=> feat(angular-v17-primeng): posts and post-detail pages

angular-v17-PrimeNG/src/app/app.routes.ts, angular-v17-PrimeNG/src/app/components/header/header.component.html, angular-v17-PrimeNG/src/app/components/header/header.component.ts, angular-v17-PrimeNG/src/app/components/series/series.component.html, angular-v17-PrimeNG/src/app/components/series/series.component.spec.ts, angular-v17-PrimeNG/src/app/components/series/series.component.ts, angular-v17-PrimeNG/src/app/graphql.operations.ts, angular-v17-PrimeNG/src/app/models/series.ts, angular-v17-PrimeNG/src/app/services/blog.service.ts
closes #216 
Added new service in blog.service.ts to retrieve seriesList data, and implemented UI routing.
- [ x] 🙅 no documentation needed
=> feature(#216): Query the actual series (topics) to display in header in v17 primeng

angular-v17-PrimeNG/src/app/pages/post-detail/post-detail.component.ts, angular-v17/src/app/components/header/header.component.html, angular-v17/src/app/components/header/header.component.ts, angular-v17/src/app/components/post-detail/post-detail.component.ts, angular-v17/src/app/components/posts/posts.component.html, angular-v17/src/app/components/posts/posts.component.ts, angular-v17/src/app/models/blog-info.ts, angular-v17/src/app/models/post.ts, angular-v17/src/app/services/blog.service.ts
=> feat(v17): standardizing, using models, observables

angular-v17-modMAT/src/app/components/header/header.component.html, angular-v17-modMAT/src/app/components/header/header.component.ts
=> feat(v17-modMAT): series list in header

angular-v17-PrimeNG/src/app/components/post-details/post-details.component.scss, angular-v17/src/app/components/post-details/post-details.component.scss
=> feat(styling): sticking to scss and relative measurements as initially set

angular-v17-AnguMAT/src/app/components/post-detail/post-detail.component.html, angular-v17-AnguMAT/src/app/components/post-detail/post-detail.component.scss, angular-v17-AnguMAT/src/app/components/post-detail/post-detail.component.ts, angular-v17-AnguMAT/src/theme.scss, angular-v17-modMAT/src/app/components/post-details/post-details.component.html, angular-v17-modMAT/src/app/components/post-details/post-details.component.scss, angular-v17-modMAT/src/theme.scss
=> feat(angumat, modmat): post-details mat-icon for tags and scss

angular-v17-AnguMAT/src/app/components/post-detail/post-detail.component.html, angular-v17-PrimeNG/src/app/components/post-details/post-details.component.html, angular-v17-modMAT/src/app/components/post-details/post-details.component.html, angular-v17/src/app/components/post-details/post-details.component.html
=> feat(all app versions): timen icon changed with open book or most similar icon

angular-v17-AnguMAT/src/app/components/header/header.component.html, angular-v17-AnguMAT/src/app/components/header/header.component.scss, angular-v17-AnguMAT/src/app/components/header/header.component.ts, angular-v17-AnguMAT/src/app/graphql.operations.ts, angular-v17-AnguMAT/src/app/models/post.ts, angular-v17-AnguMAT/src/app/services/blog.service.ts, angular-v17/src/app/components/header/header.component.scss
=> feat(anguMAT): query series in header

angular-v17/src/styles.scss
=> feat(v-17):styling minor adjustment

angular-v17-PrimeNG/src/app/components/posts/posts.component.ts, angular-v17-PrimeNG/src/app/components/series/series.component.html, angular-v17-PrimeNG/src/app/components/series/series.component.scss, angular-v17-PrimeNG/src/app/components/series/series.component.ts, angular-v17-PrimeNG/src/app/graphql.operations.ts, angular-v17-PrimeNG/src/app/services/blog.service.ts, angular-v17-modMAT/src/app/app-routing.module.ts, angular-v17-modMAT/src/app/app.module.ts, angular-v17-modMAT/src/app/components/series/series.component.html, angular-v17-modMAT/src/app/components/series/series.component.scss, angular-v17-modMAT/src/app/components/series/series.component.spec.ts, angular-v17-modMAT/src/app/components/series/series.component.ts, angular-v17/src/app/components/series/series.component.ts
=> Query & display posts from series in the series component

angular-v17/src/app/components/footer/footer.component.ts, angular-v17/src/app/components/header/header.component.ts, angular-v17/src/app/graphql.operations.ts, angular-v17/src/app/models/blog-info.ts
closes #338 
Query the blog 'favicon' or 'logo' or 'author image' in header in v17 native
=> feature(angular-v17): Query the blog 'favicon' or 'logo' or 'author image' in header in v17 native

angular-v17-modMAT/src/app/app.module.ts, angular-v17-modMAT/src/app/components/post-details/post-details.component.html, angular-v17-modMAT/src/app/components/post-details/post-details.component.ts, angular-v17-modMAT/src/app/pipes/sanitizer-html.pipe.spec.ts, angular-v17-modMAT/src/app/pipes/sanitizer-html.pipe.ts
=> feat(modmat): html sanitizer

angular-v17-PrimeNG/src/app/components/header/header.component.html, angular-v17-PrimeNG/src/app/components/header/header.component.scss, angular-v17-PrimeNG/src/app/components/header/header.component.ts, angular-v17-PrimeNG/src/app/components/post-search/post-search.component.html, angular-v17-PrimeNG/src/app/components/post-search/post-search.component.scss, angular-v17-PrimeNG/src/app/components/post-search/post-search.component.spec.ts, angular-v17-PrimeNG/src/app/components/post-search/post-search.component.ts, angular-v17-PrimeNG/src/app/graphql.operations.ts, angular-v17-PrimeNG/src/app/services/blog.service.ts, angular-v17-PrimeNG/src/assets/themes/light.scss
=> feat(angular-v17-primeng): search posts in the blog in a dialog

angular-v17-AnguMAT/src/app/components/posts/posts.component.ts, angular-v17-PrimeNG/src/app/components/posts/posts.component.html, angular-v17-PrimeNG/src/app/components/posts/posts.component.ts, angular-v17-modMAT/src/app/components/posts/posts.component.html, angular-v17-modMAT/src/app/components/posts/posts.component.ts, angular-v17/src/app/app.component.html, angular-v17/src/app/app.component.scss, angular-v17/src/app/app.component.ts, angular-v17/src/app/app.routes.ts, angular-v17/src/app/components/footer/footer.component.scss, angular-v17/src/app/components/header/header.component.ts, angular-v17/src/app/components/layout/layout.component.html, angular-v17/src/app/components/layout/layout.component.scss, angular-v17/src/app/components/layout/layout.component.spec.ts, angular-v17/src/app/components/layout/layout.component.ts, angular-v17/src/app/components/post-details/post-details.component.html, angular-v17/src/app/components/post-details/post-details.component.scss, angular-v17/src/app/components/post-details/post-details.component.ts, angular-v17/src/app/components/posts/posts.component.html, angular-v17/src/app/components/posts/posts.component.ts, angular-v17/src/app/components/sidenav/sidenav.component.html, angular-v17/src/app/components/sidenav/sidenav.component.scss, angular-v17/src/app/components/sidenav/sidenav.component.spec.ts, angular-v17/src/app/components/sidenav/sidenav.component.ts, angular-v17/src/styles.scss
closes #319 
- new layout implemented for post details, layout component added, sidenav component added
- details retrieved in relevant components 
- styling, theming and routing adjusted
- site favicon logic moved to app.component.ts
- post is not a `new` observable, it is a query response observable so this was corrected too on all apps
=> feat(v17): post details, sidenav, sitefavicon in app.component

angular-v17-AnguMAT/src/styles.scss, angular-v17/src/styles.scss
=> minor styling post details

angular-v17-AnguMAT/src/app/components/header/header.component.html, angular-v17-AnguMAT/src/app/graphql.operations.ts, angular-v17/src/app/graphql.operations.ts
=> adding id and minor

angular-v17-PrimeNG/src/app/components/post-details/post-details.component.html, angular-v17-PrimeNG/src/app/components/post-details/post-details.component.ts, angular-v17-PrimeNG/src/app/pipes/sanitizer-html.pipe.spec.ts, angular-v17-PrimeNG/src/app/pipes/sanitizer-html.pipe.ts
=> feat(angular-v17-primeng): HTML sanitizer pipe

angular-v17-AnguMAT/angular.json, angular-v17-AnguMAT/src/app/components/header/header.component.html, angular-v17-AnguMAT/src/app/components/header/header.component.scss, angular-v17-AnguMAT/src/app/components/header/header.component.ts, angular-v17-AnguMAT/src/app/graphql.operations.ts, angular-v17-AnguMAT/src/app/partials/search-dialog/search-dialog.component.html, angular-v17-AnguMAT/src/app/partials/search-dialog/search-dialog.component.scss, angular-v17-AnguMAT/src/app/partials/search-dialog/search-dialog.component.spec.ts, angular-v17-AnguMAT/src/app/partials/search-dialog/search-dialog.component.ts, angular-v17-AnguMAT/src/app/services/blog.service.ts, angular-v17-AnguMAT/src/theme.scss, angular-v17-PrimeNG/angular.json
=> feat(angular-v17-angumat): search posts in blog in dialog
